import fs from "node:fs";import path from "node:path";
import type { RealEngineReportHouseNumber, ZodiacKey } from "@/types/astro";
import { normalizeChartPlacement, type NormalizedChart } from "./normalized-chart";
import { readJplSmallBodyGeocentricBatchSync } from "./jpl-spk-wasm-provider";
import { stateToTrueEclipticOfDateLongitude } from "./jpl-main-asteroid-calculation";
export const ASTEROID_LAB_CATALOG_VERSION="halleus-asteroid-lab-v1-20260831" as const;
export type CuratedAsteroidNumber=1181|433|16|10;
export type CuratedAsteroidLabEntry={number:CuratedAsteroidNumber;spkFileId:number;labelFa:string;labelEn:string;aliases:readonly string[];collisionClarification:string|null;};
export const CURATED_ASTEROID_LAB_CATALOG:readonly CuratedAsteroidLabEntry[]=[
 {number:1181,spkFileId:20001181,labelFa:"لیلیت ۱۱۸۱",labelEn:"Asteroid 1181 Lilith",aliases:["1181","lilith","asteroid lilith","لیلیت","لیلیت ۱۱۸۱"],collisionClarification:"این جرم سیارک ۱۱۸۱ لیلیت است و با بلک مون لیلیت یکی نیست."},
 {number:433,spkFileId:20000433,labelFa:"اروس ۴۳۳",labelEn:"433 Eros",aliases:["433","eros","اروس","اروس ۴۳۳"],collisionClarification:"این جرم سیارک ۴۳۳ اروس است و با سهم اروس (Lot of Eros) یکی نیست."},
 {number:16,spkFileId:20000016,labelFa:"سایکی ۱۶",labelEn:"16 Psyche",aliases:["16","psyche","سایکی","سایکی ۱۶"],collisionClarification:null},
 {number:10,spkFileId:20000010,labelFa:"هایجیا ۱۰",labelEn:"10 Hygiea",aliases:["10","hygiea","hygeia","هایجیا","هایجیا ۱۰"],collisionClarification:null},
] as const;
const ZODIAC:ZodiacKey[]=["aries","taurus","gemini","cancer","leo","virgo","libra","scorpio","sagittarius","capricorn","aquarius","pisces"];
function digits(s:string){return s.replace(/[۰-۹]/g,c=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(c))).replace(/[٠-٩]/g,c=>String("٠١٢٣٤٥٦٧٨٩".indexOf(c)));}
function q(s:string){return digits(s).trim().toLocaleLowerCase("fa-IR").replace(/\s+/g," ");}
export function searchAsteroidLabCatalog(query:string):{status:"found";entry:CuratedAsteroidLabEntry}|{status:"not-found";query:string;message:string}{const n=q(query);if(!n)return{status:"not-found",query,message:"نام یا شمارهٔ سیارک را وارد کن."};const matches=CURATED_ASTEROID_LAB_CATALOG.filter(e=>e.aliases.some(a=>q(a)===n));if(matches.length===1)return{status:"found",entry:matches[0]};return{status:"not-found",query,message:"این سیارک در کاتالوگ فعلی Asteroid Lab پشتیبانی نشده است."};}
export type AsteroidLabCalculation={status:"calculated";stableId:`asteroid:${CuratedAsteroidNumber}`;number:CuratedAsteroidNumber;labelFa:string;labelEn:string;longitude:number;signId:ZodiacKey;degreeInSign:number;house:RealEngineReportHouseNumber|null;motion:{status:"direct"|"retrograde"|"stationary";arcDegreesPerDay:number;sampleWindowHours:12;};source:"local-jpl-horizons-spk";catalogueVersion:typeof ASTEROID_LAB_CATALOG_VERSION;collisionClarification:string|null;mainReportPromotion:"not-automatic";}|{status:"blocked";number:CuratedAsteroidNumber;labelFa:string;labelEn:string;reason:"missing-ephemeris-files"|"provider-unavailable"|"invalid-provider-output";detail:string;collisionClarification:string|null;};
function norm(v:number){const n=v%360;return n<0?n+360:n;}function diff(a:number,b:number){let d=norm(a)-norm(b);if(d>180)d-=360;if(d<-180)d+=360;return d;}
function houseFor(longitude:number,chart:NormalizedChart,id:string,label:string):RealEngineReportHouseNumber|null{if(!chart.houseContext.housesReady||chart.houses.length!==12)return null;return normalizeChartPlacement({id,label,pointType:"calculated-point",longitude},chart.houseContext.firstHouseCuspLongitude,chart.houseContext.appliedSystem,chart.houses).house.house;}
export function calculateCuratedAsteroidLab(input:{entry:CuratedAsteroidLabEntry;utcDate:Date;chart:NormalizedChart;kernelDirectory?:string|null;}):AsteroidLabCalculation{const dir=input.kernelDirectory?.trim()||process.env.HALLEUS_ADVANCED_EPHEMERIS_DIR?.trim()||"";const common=["naif0012.tls","de440s.bsp"];const body=`${input.entry.spkFileId}.bsp`;if(!dir||[...common,body].some(f=>!fs.existsSync(path.join(dir,f))))return{status:"blocked",number:input.entry.number,labelFa:input.entry.labelFa,labelEn:input.entry.labelEn,reason:"missing-ephemeris-files",detail:"Asteroid Lab requires pinned local JPL kernels; it never invents or approximates a longitude.",collisionClarification:input.entry.collisionClarification};const requests=[[-12,"before"],[0,"current"],[12,"after"]] as const;const targetId=`asteroid-${input.entry.number}` as `asteroid-${number}`;const batch=readJplSmallBodyGeocentricBatchSync({kernelPaths:[path.join(dir,"naif0012.tls"),path.join(dir,"de440s.bsp"),path.join(dir,body),path.join(dir,body)],requests:requests.map(([h,label])=>({key:label,targetId,spkFileId:input.entry.spkFileId,utcDate:new Date(input.utcDate.getTime()+h*3600000)}))});if(batch.status!=="ready")return{status:"blocked",number:input.entry.number,labelFa:input.entry.labelFa,labelEn:input.entry.labelEn,reason:batch.reason,detail:batch.detail,collisionClarification:input.entry.collisionClarification};const m=new Map(batch.results.map(r=>[r.key,r]));const b=m.get("before"),c=m.get("current"),a=m.get("after");if(!b||!c||!a)return{status:"blocked",number:input.entry.number,labelFa:input.entry.labelFa,labelEn:input.entry.labelEn,reason:"invalid-provider-output",detail:"Asteroid Lab state sampling was incomplete.",collisionClarification:input.entry.collisionClarification};const bl=stateToTrueEclipticOfDateLongitude(b.stateKmAndKmPerSecond,new Date(b.utcIso)),cl=stateToTrueEclipticOfDateLongitude(c.stateKmAndKmPerSecond,new Date(c.utcIso)),al=stateToTrueEclipticOfDateLongitude(a.stateKmAndKmPerSecond,new Date(a.utcIso)),arc=diff(al,bl),status=Math.abs(arc)<=0.01?"stationary":arc<0?"retrograde":"direct",si=Math.floor(cl/30)%12;return{status:"calculated",stableId:`asteroid:${input.entry.number}`,number:input.entry.number,labelFa:input.entry.labelFa,labelEn:input.entry.labelEn,longitude:cl,signId:ZODIAC[si],degreeInSign:cl-si*30,house:houseFor(cl,input.chart,`asteroid:${input.entry.number}`,input.entry.labelEn),motion:{status,arcDegreesPerDay:arc,sampleWindowHours:12},source:"local-jpl-horizons-spk",catalogueVersion:ASTEROID_LAB_CATALOG_VERSION,collisionClarification:input.entry.collisionClarification,mainReportPromotion:"not-automatic"};}
