import type {
  AstroElement,
  AstroModality,
  AstroPolarity,
  EngineChartPoint,
  ZodiacSymbolProfile,
} from "./types";
import type { ZodiacKey } from "@/types/astro";

export const elementLabels: Record<AstroElement, string> = {
  fire: "آتش",
  earth: "خاک",
  air: "هوا",
  water: "آب",
};

export const modalityLabels: Record<AstroModality, string> = {
  cardinal: "آغازگر",
  fixed: "ثابت",
  mutable: "منعطف",
};

export const polarityLabels: Record<AstroPolarity, string> = {
  yang: "بیرونی / فعال",
  yin: "درونی / دریافت‌گر",
};

export const chartPointLabels: Record<EngineChartPoint, string> = {
  sun: "خورشید",
  moon: "ماه",
  rising: "طالع",
};

export const zodiacKnowledge: Record<ZodiacKey, ZodiacSymbolProfile> = {
  aries: {
    key: "aries",
    faName: "حمل",
    enName: "Aries",
    element: "fire",
    modality: "cardinal",
    polarity: "yang",
    keywords: ["شروع", "حرکت", "جرئت", "مستقیم‌بودن"],
    symbolicSummary: "حمل به شکل نمادین با شروع، حرکت سریع و میل به تجربه مستقیم پیوند دارد.",
  },
  taurus: {
    key: "taurus",
    faName: "ثور",
    enName: "Taurus",
    element: "earth",
    modality: "fixed",
    polarity: "yin",
    keywords: ["ثبات", "بدن", "امنیت", "ارزش"],
    symbolicSummary: "ثور به شکل نمادین با ثبات، لمس‌پذیری، امنیت و رابطه با ارزش‌ها پیوند دارد.",
  },
  gemini: {
    key: "gemini",
    faName: "جوزا",
    enName: "Gemini",
    element: "air",
    modality: "mutable",
    polarity: "yang",
    keywords: ["فکر", "گفت‌وگو", "کنجکاوی", "ارتباط"],
    symbolicSummary: "جوزا به شکل نمادین با کنجکاوی، زبان، ارتباط و جابه‌جایی ذهنی پیوند دارد.",
  },
  cancer: {
    key: "cancer",
    faName: "سرطان",
    enName: "Cancer",
    element: "water",
    modality: "cardinal",
    polarity: "yin",
    keywords: ["احساس", "خانه", "حافظه", "مراقبت"],
    symbolicSummary: "سرطان به شکل نمادین با مراقبت، خاطره، خانه و واکنش احساسی پیوند دارد.",
  },
  leo: {
    key: "leo",
    faName: "اسد",
    enName: "Leo",
    element: "fire",
    modality: "fixed",
    polarity: "yang",
    keywords: ["بیان", "خلاقیت", "قلب", "حضور"],
    symbolicSummary: "اسد به شکل نمادین با حضور، خلاقیت، بیان شخصی و گرمای قلب پیوند دارد.",
  },
  virgo: {
    key: "virgo",
    faName: "سنبله",
    enName: "Virgo",
    element: "earth",
    modality: "mutable",
    polarity: "yin",
    keywords: ["دقت", "بهبود", "خدمت", "جزئیات"],
    symbolicSummary: "سنبله به شکل نمادین با دقت، اصلاح، خدمت و توجه به جزئیات پیوند دارد.",
  },
  libra: {
    key: "libra",
    faName: "میزان",
    enName: "Libra",
    element: "air",
    modality: "cardinal",
    polarity: "yang",
    keywords: ["رابطه", "تعادل", "زیبایی", "مذاکره"],
    symbolicSummary: "میزان به شکل نمادین با رابطه، تعادل، زیبایی و دیدن طرف دیگر پیوند دارد.",
  },
  scorpio: {
    key: "scorpio",
    faName: "عقرب",
    enName: "Scorpio",
    element: "water",
    modality: "fixed",
    polarity: "yin",
    keywords: ["عمق", "دگرگونی", "راز", "شدت"],
    symbolicSummary: "عقرب به شکل نمادین با عمق، دگرگونی، صمیمیت و مواجهه با لایه‌های پنهان پیوند دارد.",
  },
  sagittarius: {
    key: "sagittarius",
    faName: "قوس",
    enName: "Sagittarius",
    element: "fire",
    modality: "mutable",
    polarity: "yang",
    keywords: ["معنا", "سفر", "باور", "افق"],
    symbolicSummary: "قوس به شکل نمادین با جست‌وجوی معنا، افق‌های تازه، یادگیری و حرکت پیوند دارد.",
  },
  capricorn: {
    key: "capricorn",
    faName: "جدی",
    enName: "Capricorn",
    element: "earth",
    modality: "cardinal",
    polarity: "yin",
    keywords: ["ساختار", "مسئولیت", "زمان", "بلوغ"],
    symbolicSummary: "جدی به شکل نمادین با ساختار، مسئولیت، زمان و ساختن تدریجی پیوند دارد.",
  },
  aquarius: {
    key: "aquarius",
    faName: "دلو",
    enName: "Aquarius",
    element: "air",
    modality: "fixed",
    polarity: "yang",
    keywords: ["آینده", "گروه", "استقلال", "ایده"],
    symbolicSummary: "دلو به شکل نمادین با ایده، آینده، فاصله سالم و نگاه جمعی پیوند دارد.",
  },
  pisces: {
    key: "pisces",
    faName: "حوت",
    enName: "Pisces",
    element: "water",
    modality: "mutable",
    polarity: "yin",
    keywords: ["رؤیا", "همدلی", "مرز", "خیال"],
    symbolicSummary: "حوت به شکل نمادین با همدلی، خیال، حساسیت و مرزهای نرم پیوند دارد.",
  },
};
