import type {
  AstroElement,
  AstroModality,
  AstroPolarity,
  EngineChartPoint,
  ZodiacSymbolProfile,
} from "./types";
import type { ZodiacKey } from "@/types/astro";

export const elementLabels: Record<AstroElement, string> = {
  fire: "Ø¢ØªØ´",
  earth: "Ø®Ø§Ú©",
  air: "Ù‡ÙˆØ§",
  water: "Ø¢Ø¨",
};

export const modalityLabels: Record<AstroModality, string> = {
  cardinal: "Ø¢ØºØ§Ø²Ú¯Ø±",
  fixed: "Ø«Ø§Ø¨Øª",
  mutable: "Ù…Ù†Ø¹Ø·Ù",
};

export const polarityLabels: Record<AstroPolarity, string> = {
  yang: "Ø¨ÛŒØ±ÙˆÙ†ÛŒ / ÙØ¹Ø§Ù„",
  yin: "Ø¯Ø±ÙˆÙ†ÛŒ / Ø¯Ø±ÛŒØ§ÙØªâ€ŒÚ¯Ø±",
};

export const chartPointLabels: Record<EngineChartPoint, string> = {
  sun: "Ø®ÙˆØ±Ø´ÛŒØ¯",
  moon: "Ù…Ø§Ù‡",
  rising: "Ø·Ø§Ù„Ø¹",
};

export const zodiacKnowledge: Record<ZodiacKey, ZodiacSymbolProfile> = {
  aries: {
    key: "aries",
    faName: "Ø­Ù…Ù„",
    enName: "Aries",
    element: "fire",
    modality: "cardinal",
    polarity: "yang",
    keywords: ["Ø´Ø±ÙˆØ¹", "Ø­Ø±Ú©Øª", "Ø¬Ø±Ø¦Øª", "Ù…Ø³ØªÙ‚ÛŒÙ…â€ŒØ¨ÙˆØ¯Ù†"],
    symbolicSummary: "Ø­Ù…Ù„ Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø´Ø±ÙˆØ¹ØŒ Ø­Ø±Ú©Øª Ø³Ø±ÛŒØ¹ Ùˆ Ù…ÛŒÙ„ Ø¨Ù‡ ØªØ¬Ø±Ø¨Ù‡ Ù…Ø³ØªÙ‚ÛŒÙ… Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  taurus: {
    key: "taurus",
    faName: "Ø«ÙˆØ±",
    enName: "Taurus",
    element: "earth",
    modality: "fixed",
    polarity: "yin",
    keywords: ["Ø«Ø¨Ø§Øª", "Ø¨Ø¯Ù†", "Ø§Ù…Ù†ÛŒØª", "Ø§Ø±Ø²Ø´"],
    symbolicSummary: "Ø«ÙˆØ± Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø«Ø¨Ø§ØªØŒ Ù„Ù…Ø³â€ŒÙ¾Ø°ÛŒØ±ÛŒØŒ Ø§Ù…Ù†ÛŒØª Ùˆ Ø±Ø§Ø¨Ø·Ù‡ Ø¨Ø§ Ø§Ø±Ø²Ø´â€ŒÙ‡Ø§ Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  gemini: {
    key: "gemini",
    faName: "Ø¬ÙˆØ²Ø§",
    enName: "Gemini",
    element: "air",
    modality: "mutable",
    polarity: "yang",
    keywords: ["ÙÚ©Ø±", "Ú¯ÙØªâ€ŒÙˆÚ¯Ùˆ", "Ú©Ù†Ø¬Ú©Ø§ÙˆÛŒ", "Ø§Ø±ØªØ¨Ø§Ø·"],
    symbolicSummary: "Ø¬ÙˆØ²Ø§ Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ú©Ù†Ø¬Ú©Ø§ÙˆÛŒØŒ Ø²Ø¨Ø§Ù†ØŒ Ø§Ø±ØªØ¨Ø§Ø· Ùˆ Ø¬Ø§Ø¨Ù‡â€ŒØ¬Ø§ÛŒÛŒ Ø°Ù‡Ù†ÛŒ Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  cancer: {
    key: "cancer",
    faName: "Ø³Ø±Ø·Ø§Ù†",
    enName: "Cancer",
    element: "water",
    modality: "cardinal",
    polarity: "yin",
    keywords: ["Ø§Ø­Ø³Ø§Ø³", "Ø®Ø§Ù†Ù‡", "Ø­Ø§ÙØ¸Ù‡", "Ù…Ø±Ø§Ù‚Ø¨Øª"],
    symbolicSummary: "Ø³Ø±Ø·Ø§Ù† Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ù…Ø±Ø§Ù‚Ø¨ØªØŒ Ø®Ø§Ø·Ø±Ù‡ØŒ Ø®Ø§Ù†Ù‡ Ùˆ ÙˆØ§Ú©Ù†Ø´ Ø§Ø­Ø³Ø§Ø³ÛŒ Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  leo: {
    key: "leo",
    faName: "Ø§Ø³Ø¯",
    enName: "Leo",
    element: "fire",
    modality: "fixed",
    polarity: "yang",
    keywords: ["Ø¨ÛŒØ§Ù†", "Ø®Ù„Ø§Ù‚ÛŒØª", "Ù‚Ù„Ø¨", "Ø­Ø¶ÙˆØ±"],
    symbolicSummary: "Ø§Ø³Ø¯ Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø­Ø¶ÙˆØ±ØŒ Ø®Ù„Ø§Ù‚ÛŒØªØŒ Ø¨ÛŒØ§Ù† Ø´Ø®ØµÛŒ Ùˆ Ú¯Ø±Ù…Ø§ÛŒ Ù‚Ù„Ø¨ Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  virgo: {
    key: "virgo",
    faName: "Ø³Ù†Ø¨Ù„Ù‡",
    enName: "Virgo",
    element: "earth",
    modality: "mutable",
    polarity: "yin",
    keywords: ["Ø¯Ù‚Øª", "Ø¨Ù‡Ø¨ÙˆØ¯", "Ø®Ø¯Ù…Øª", "Ø¬Ø²Ø¦ÛŒØ§Øª"],
    symbolicSummary: "Ø³Ù†Ø¨Ù„Ù‡ Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø¯Ù‚ØªØŒ Ø§ØµÙ„Ø§Ø­ØŒ Ø®Ø¯Ù…Øª Ùˆ ØªÙˆØ¬Ù‡ Ø¨Ù‡ Ø¬Ø²Ø¦ÛŒØ§Øª Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  libra: {
    key: "libra",
    faName: "Ù…ÛŒØ²Ø§Ù†",
    enName: "Libra",
    element: "air",
    modality: "cardinal",
    polarity: "yang",
    keywords: ["Ø±Ø§Ø¨Ø·Ù‡", "ØªØ¹Ø§Ø¯Ù„", "Ø²ÛŒØ¨Ø§ÛŒÛŒ", "Ù…Ø°Ø§Ú©Ø±Ù‡"],
    symbolicSummary: "Ù…ÛŒØ²Ø§Ù† Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø±Ø§Ø¨Ø·Ù‡ØŒ ØªØ¹Ø§Ø¯Ù„ØŒ Ø²ÛŒØ¨Ø§ÛŒÛŒ Ùˆ Ø¯ÛŒØ¯Ù† Ø·Ø±Ù Ø¯ÛŒÚ¯Ø± Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  scorpio: {
    key: "scorpio",
    faName: "Ø¹Ù‚Ø±Ø¨",
    enName: "Scorpio",
    element: "water",
    modality: "fixed",
    polarity: "yin",
    keywords: ["Ø¹Ù…Ù‚", "Ø¯Ú¯Ø±Ú¯ÙˆÙ†ÛŒ", "Ø±Ø§Ø²", "Ø´Ø¯Øª"],
    symbolicSummary: "Ø¹Ù‚Ø±Ø¨ Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø¹Ù…Ù‚ØŒ Ø¯Ú¯Ø±Ú¯ÙˆÙ†ÛŒØŒ ØµÙ…ÛŒÙ…ÛŒØª Ùˆ Ù…ÙˆØ§Ø¬Ù‡Ù‡ Ø¨Ø§ Ù„Ø§ÛŒÙ‡â€ŒÙ‡Ø§ÛŒ Ù¾Ù†Ù‡Ø§Ù† Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  sagittarius: {
    key: "sagittarius",
    faName: "Ù‚ÙˆØ³",
    enName: "Sagittarius",
    element: "fire",
    modality: "mutable",
    polarity: "yang",
    keywords: ["Ù…Ø¹Ù†Ø§", "Ø³ÙØ±", "Ø¨Ø§ÙˆØ±", "Ø§ÙÙ‚"],
    symbolicSummary: "Ù‚ÙˆØ³ Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø¬Ø³Øªâ€ŒÙˆØ¬ÙˆÛŒ Ù…Ø¹Ù†Ø§ØŒ Ø§ÙÙ‚â€ŒÙ‡Ø§ÛŒ ØªØ§Ø²Ù‡ØŒ ÛŒØ§Ø¯Ú¯ÛŒØ±ÛŒ Ùˆ Ø­Ø±Ú©Øª Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  capricorn: {
    key: "capricorn",
    faName: "Ø¬Ø¯ÛŒ",
    enName: "Capricorn",
    element: "earth",
    modality: "cardinal",
    polarity: "yin",
    keywords: ["Ø³Ø§Ø®ØªØ§Ø±", "Ù…Ø³Ø¦ÙˆÙ„ÛŒØª", "Ø²Ù…Ø§Ù†", "Ø¨Ù„ÙˆØº"],
    symbolicSummary: "Ø¬Ø¯ÛŒ Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø³Ø§Ø®ØªØ§Ø±ØŒ Ù…Ø³Ø¦ÙˆÙ„ÛŒØªØŒ Ø²Ù…Ø§Ù† Ùˆ Ø³Ø§Ø®ØªÙ† ØªØ¯Ø±ÛŒØ¬ÛŒ Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  aquarius: {
    key: "aquarius",
    faName: "Ø¯Ù„Ùˆ",
    enName: "Aquarius",
    element: "air",
    modality: "fixed",
    polarity: "yang",
    keywords: ["Ø¢ÛŒÙ†Ø¯Ù‡", "Ú¯Ø±ÙˆÙ‡", "Ø§Ø³ØªÙ‚Ù„Ø§Ù„", "Ø§ÛŒØ¯Ù‡"],
    symbolicSummary: "Ø¯Ù„Ùˆ Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ø§ÛŒØ¯Ù‡ØŒ Ø¢ÛŒÙ†Ø¯Ù‡ØŒ ÙØ§ØµÙ„Ù‡ Ø³Ø§Ù„Ù… Ùˆ Ù†Ú¯Ø§Ù‡ Ø¬Ù…Ø¹ÛŒ Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
  pisces: {
    key: "pisces",
    faName: "Ø­ÙˆØª",
    enName: "Pisces",
    element: "water",
    modality: "mutable",
    polarity: "yin",
    keywords: ["Ø±Ø¤ÛŒØ§", "Ù‡Ù…Ø¯Ù„ÛŒ", "Ù…Ø±Ø²", "Ø®ÛŒØ§Ù„"],
    symbolicSummary: "Ø­ÙˆØª Ø¨Ù‡ Ø´Ú©Ù„ Ù†Ù…Ø§Ø¯ÛŒÙ† Ø¨Ø§ Ù‡Ù…Ø¯Ù„ÛŒØŒ Ø®ÛŒØ§Ù„ØŒ Ø­Ø³Ø§Ø³ÛŒØª Ùˆ Ù…Ø±Ø²Ù‡Ø§ÛŒ Ù†Ø±Ù… Ù¾ÛŒÙˆÙ†Ø¯ Ø¯Ø§Ø±Ø¯.",
  },
};
