// HALLEUS_DEEP_NARRATIVE_SLICE5_FINAL_VISUAL_LANGUAGE_RECONCILIATION_R2_20260903
// HALLEUS_DEEP_NARRATIVE_SLICE2_FAILURESET_RECONCILIATION_R3_20260902
// HALLEUS_DEEP_NARRATIVE_SLICE2_CANONICAL_PLACEMENT_MATRIX_R2_20260902
export type CanonicalPlanetId = "sun" | "moon" | "mercury" | "venus" | "mars" | "jupiter" | "saturn" | "uranus" | "neptune" | "pluto";
export type CanonicalSignId = "aries" | "taurus" | "gemini" | "cancer" | "leo" | "virgo" | "libra" | "scorpio" | "sagittarius" | "capricorn" | "aquarius" | "pisces";
export type CanonicalHouseNumber = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;
export type CanonicalAudienceMode = "adult" | "youth" | "caregiver";
export type CanonicalPlacementNarrative = { semanticKey: string; thesis: string; mechanism: string; contextExpression: string; everydayScene: string; constructiveExpression: string; frictionExpression: string; focus: string; actionCue: string; specificity: "targeted" | "matrix-composed"; facts: { planetId: CanonicalPlanetId; signId: CanonicalSignId; houseNumber: CanonicalHouseNumber; retrograde: boolean; sourceRefs: string[]; }; };
export type CanonicalHouseNarrative = { semanticKey: string; thesis: string; synthesis: string; everydayScene: string; constructiveExpression: string; frictionExpression: string; actionCue: string; memberSemanticKeys: string[]; };
type PlanetProfile = { label: string; function: string; operation: string; strength: string; shadow: string; action: string; };
type SignProfile = { label: string; method: string; priority: string; strength: string; shadow: string; action: string; };
type HouseProfile = { field: string; scene: string; outcome: string; shadow: string; action: string; };
const PLANETS: Record<CanonicalPlanetId, PlanetProfile> = {
  sun: { label: "خورشید", function: "هویت و حق انتخاب", operation: "انتخاب را با امضای شخصی نشان دهد", strength: "حضور روشن و خلاقیت شخصی", shadow: "نیاز به حفظ تصویر یا تأیید بیرونی", action: "یک انتخاب شخصی را تا نتیجه‌ای قابل دیدن پیش ببرد" },
  moon: { label: "ماه", function: "امنیت عاطفی و ریتم واکنش", operation: "نیاز را به احساس امنیت و تنظیم بدن وصل کند", strength: "مراقبت و تشخیص دقیق نیاز", shadow: "واکنش پیش از نام‌گذاری احساس یا چسبیدن به امنیت آشنا", action: "احساس، نیاز و درخواست را از هم جدا کند" },
  mercury: { label: "عطارد", function: "فکر، نام‌گذاری و تصمیم", operation: "اطلاعات را به فهم، زبان و تصمیم تبدیل کند", strength: "وضوح، کنجکاوی و پیوند دادن ایده‌ها", shadow: "پخش شدن میان احتمال‌ها یا تحلیل بی‌پایان", action: "مسئله را به دانسته، نادانسته و قدم بعدی تقسیم کند" },
  venus: { label: "زهره", function: "ارزش، لذت و نزدیکی", operation: "ترجیح و ارزش را به انتخاب رابطه‌ای تبدیل کند", strength: "نزدیکی همراه با انتخاب و مرز", shadow: "سنجیدن ارزش خود از واکنش دیگری یا نگفتن نارضایتی", action: "یک ترجیح و یک مرز را هم‌زمان روشن کند" },
  mars: { label: "مریخ", function: "خواستن، اقدام و دفاع از مرز", operation: "میل را به حرکت، درخواست یا دفاع عملی تبدیل کند", strength: "جرئت و اقدام روشن", shadow: "عجله، انباشت خشم یا اقدام پیش از فهم خواسته", action: "خواسته را به کوچک‌ترین اقدام روشن تبدیل کند" },
  jupiter: { label: "مشتری", function: "گسترش، معنا و فرصت", operation: "افق بزرگ‌تر را به تجربه و امکان واقعی وصل کند", strength: "امید، بخشندگی و دیدن امکان", shadow: "قول بزرگ، پراکندگی یا رها کردن جزئیات بعد از هیجان", action: "یک امکان را در مقیاس کوچک تا پایان آزمایش کند" },
  saturn: { label: "زحل", function: "مرز، زمان و مسئولیت", operation: "محدودیت را به ساختار و مهارت پایدار تبدیل کند", strength: "پایداری، مرزبندی و قابلیت اتکا", shadow: "خودسانسوری، ترس از خطا یا دیر شروع کردن", action: "یک مسئولیت را به قدم کوتاه با پایان مشخص تبدیل کند" },
  uranus: { label: "اورانوس", function: "آزادی، تازگی و تغییر الگو", operation: "راه متفاوت را در برابر تکرار یا محدودیت پیدا کند", strength: "نوآوری، استقلال و دیدن راه تازه", shadow: "قطع ناگهانی، بی‌حوصلگی از ادامه یا تغییر غیرقابل‌برگشت", action: "تغییر را اول به شکل کوچک و برگشت‌پذیر امتحان کند" },
  neptune: { label: "نپتون", function: "تخیل، حساسیت و ابهام", operation: "دریافت ظریف را به معنا وصل کند و هم‌زمان واقعیت را بررسی کند", strength: "همدلی و تخیل همراه با مرز", shadow: "فرض کردن حس درونی به‌عنوان حقیقت یا حل شدن در فضای دیگری", action: "دریافت را با یک شاهد یا سؤال مستقیم بررسی کند" },
  pluto: { label: "پلوتو", function: "قدرت، شدت و بازسازی", operation: "ریشه ترس یا کنترل را به تغییر عمیق تبدیل کند", strength: "تاب‌آوری و صداقت با لایه‌های پنهان", shadow: "کنترل پنهان، همه‌یا‌هیچ دیدن یا نگه داشتن از ترس آسیب‌پذیری", action: "بخش قابل کنترل را از بخش غیرقابل کنترل جدا کند" },
};
const SIGNS: Record<CanonicalSignId, SignProfile> = {
  aries: { label: "حمل", method: "شروع مستقیم و تصمیم سریع", priority: "استقلال و حرکت", strength: "جرئت آغاز", shadow: "عجله می‌تواند جای روشن‌کردن اولویت را بگیرد", action: "پیش از شروع معیار پایان را مشخص کند" },
  taurus: { label: "ثور", method: "ریتم آهسته، ملموس و تکرارشونده", priority: "ثبات و امنیت محسوس", strength: "پایداری و حس واقعیت", shadow: "آشنایی می‌تواند تغییر لازم را عقب بیندازد", action: "تغییر را با یک گام کوچک و قابل لمس پیش ببرد" },
  gemini: { label: "جوزا", method: "پرسش، مقایسه و جابه‌جایی میان زاویه‌ها", priority: "اطلاعات و تنوع", strength: "انعطاف ذهنی و زبان زنده", shadow: "گزینه‌های زیاد می‌توانند تصمیم را پخش کنند", action: "پس از دیدن دو گزینه یکی را برای آزمایش انتخاب کند" },
  cancer: { label: "سرطان", method: "توجه به تعلق، حافظه و امنیت عاطفی", priority: "مراقبت و پیوند", strength: "حساسیت به نیاز و فضا", shadow: "حفظ پیوند می‌تواند خواسته شخصی را پنهان کند", action: "نیاز را پیش از مراقبت از دیگری نام ببرد" },
  leo: { label: "اسد", method: "بیان گرم، خلاق و قابل مشاهده", priority: "خودابرازی و شأن شخصی", strength: "جرئت دیده شدن و ساختن", shadow: "نیاز به تأیید می‌تواند نتیجه را هدایت کند", action: "کار را پیش از سنجیدن واکنش دیگران کامل کند" },
  virgo: { label: "سنبله", method: "تحلیل دقیق و حرکت مرحله‌به‌مرحله", priority: "کارآمدی و اصلاح", strength: "تشخیص جزئیات و بهبود", shadow: "کامل‌گرایی می‌تواند حرکت را عقب بیندازد", action: "نسخه کافی را پیش از کامل‌سازی تحویل دهد" },
  libra: { label: "میزان", method: "سنجیدن دو طرف و تنظیم رابطه", priority: "تعادل و مذاکره", strength: "دیدن پیامد رابطه‌ای تصمیم", shadow: "سنجیدن دیگری می‌تواند خواسته شخصی را دیر کند", action: "خواسته را پیش از دلخوری مستقیم بگوید" },
  scorpio: { label: "عقرب", method: "حرکت عمیق، متمرکز و اعتمادمحور", priority: "شدت و حقیقت پنهان", strength: "وفاداری و تحمل عمق", shadow: "ترس از آسیب‌پذیری می‌تواند به کنترل تبدیل شود", action: "نگرانی را به‌جای آزمون پنهانی بیان کند" },
  sagittarius: { label: "قوس", method: "دیدن تصویر بزرگ از راه تجربه و معنا", priority: "افق و آزادی فکری", strength: "امید و جهت‌گیری", shadow: "هیجان بزرگ می‌تواند جزئیات را کنار بزند", action: "ادعا را با یک تجربه یا نمونه واقعی بررسی کند" },
  capricorn: { label: "جدی", method: "حرکت ساختاری، مسئولانه و پیگیر", priority: "نتیجه و قابلیت اتکا", strength: "توان ساختن در زمان", shadow: "ترس از خطا می‌تواند شروع را عقب بیندازد", action: "قدم بعدی و زمان پایان را مشخص کند" },
  aquarius: { label: "دلو", method: "فاصله ذهنی، دیدن الگو و راه متفاوت", priority: "استقلال و نوآوری", strength: "اصالت و دیدن امکان تازه", shadow: "فاصله فکری می‌تواند گفت‌وگوی مستقیم را عقب بیندازد", action: "تغییر را ابتدا به شکل آزمایشی و برگشت‌پذیر اجرا کند" },
  pisces: { label: "حوت", method: "دریافت شهودی، انعطاف و حساسیت به فضا", priority: "همدلی و تخیل", strength: "توان دریافت ظرافت", shadow: "مرز میان حس و واقعیت بررسی‌شده می‌تواند کمرنگ شود", action: "حس را با یک شاهد واقعی بسنجد" },
};
const HOUSES: Record<CanonicalHouseNumber, HouseProfile> = {
  1: { field: "بدن، حضور و شروع", scene: "در شروع یک کار، معرفی خود یا موقعیتی که باید سریع موضع بگیری", outcome: "حضور شخصی را قابل دیدن کند", shadow: "واکنش فوری می‌تواند پیش از شناخت خواسته واقعی جلو بیفتد", action: "یک شروع واقعی را انتخاب و اولین قدمش را روشن کند" },
  2: { field: "ارزش، امنیت و منابع", scene: "در خرید، قیمت‌گذاری، پس‌انداز یا تصمیمی که حس امنیت را درگیر می‌کند", outcome: "ارزش را به معیار ملموس تبدیل کند", shadow: "ترس از کمبود می‌تواند انعطاف یا لذت را محدود کند", action: "یک معیار روشن برای کافی بودن تعریف کند" },
  3: { field: "فکر، یادگیری و ارتباط", scene: "در پیام، گفت‌وگو، یادگیری یا رفت‌وآمد روزمره", outcome: "فکر را به زبان و تبادل زنده تبدیل کند", shadow: "حجم اطلاعات می‌تواند تمرکز را بشکند", action: "یک موضوع را در چند جمله روشن و قابل پاسخ بیان کند" },
  4: { field: "خانه، ریشه و امنیت درونی", scene: "در خانه، خانواده یا وقتی نیاز به عقب‌نشینی و احساس تعلق بالا می‌رود", outcome: "پایه درونی و حس خانه را بسازد", shadow: "الگوی قدیمی امنیت می‌تواند تغییر را دشوار کند", action: "یک تغییر کوچک برای امن‌تر شدن فضای خصوصی انجام دهد" },
  5: { field: "خلاقیت، عشق و بیان شخصی", scene: "در پروژه شخصی، عشق، بازی یا چیزی که قرار است امضای خودت را داشته باشد", outcome: "میل شخصی را به خروجی خلاق و قابل دیدن تبدیل کند", shadow: "هیجان شروع یا نیاز به دیده شدن می‌تواند پایان را عقب بیندازد", action: "یک خروجی کوچک را با نام و انتخاب خودت تمام کند" },
  6: { field: "کار روزمره، بدن و مراقبت", scene: "در برنامه روزانه، کار، عادت یا وقتی بدن به نظم بیشتری نیاز دارد", outcome: "نیت را به تکرار و مهارت روزانه تبدیل کند", shadow: "مفید بودن می‌تواند جای استراحت یا احساس را بگیرد", action: "یک عادت ده‌دقیقه‌ای با زمان پایان مشخص بسازد" },
  7: { field: "رابطه و شراکت", scene: "در توافق، اختلاف، قرار یا تصمیمی که پاسخ طرف مقابل مهم است", outcome: "استقلال را به همکاری قابل اتکا تبدیل کند", shadow: "حفظ رابطه می‌تواند خواسته یا مرز شخصی را عقب بیندازد", action: "یک خواسته و یک تعهد قابل مذاکره را روشن بیان کند" },
  8: { field: "اعتماد، صمیمیت و منابع مشترک", scene: "در صمیمیت، اعتماد، پول مشترک یا موقعیتی که کنترل کامل ممکن نیست", outcome: "عمق را با اعتماد تدریجی و سهم روشن همراه کند", shadow: "ترس از آسیب‌پذیری می‌تواند کنترل را زیاد کند", action: "سهم، نگرانی و مرز را بدون آزمون پنهانی بیان کند" },
  9: { field: "معنا، باور و افق تازه", scene: "در سفر، یادگیری عمیق یا وقتی یک باور باید با تجربه واقعی روبه‌رو شود", outcome: "تجربه را به موضع و معنای شخصی تبدیل کند", shadow: "پاسخ بزرگ می‌تواند جزئیات خلاف انتظار را نادیده بگیرد", action: "یک باور را با تجربه یا منبع مخالف آزمایش کند" },
  10: { field: "مسیر اجتماعی و اثر بیرونی", scene: "در کار، مسئولیت عمومی یا وقتی نتیجه باید برای دیگران قابل دیدن باشد", outcome: "توان را به نتیجه، نقش و اعتبار پایدار تبدیل کند", shadow: "ارزش شخصی می‌تواند بیش از حد به عملکرد گره بخورد", action: "یک خروجی قابل تحویل با زمان پایان مشخص تعریف کند" },
  11: { field: "دوستی، جمع و آینده", scene: "در گروه، همکاری، دوستی یا برنامه‌ای که به آینده مشترک مربوط است", outcome: "فردیت را به شبکه و آینده مشترک وصل کند", shadow: "تعلق به جمع می‌تواند خواست شخصی را کم‌رنگ کند", action: "در یک جمع سهم شخصی و درخواست مشخص را بیان کند" },
  12: { field: "خلوت، ناخودآگاه و رهاسازی", scene: "در خلوت، خستگی، پایان یک چرخه یا وقتی پاسخ فوری در دسترس نیست", outcome: "فضای درونی را به استراحت، دریافت و رهاسازی تبدیل کند", shadow: "عقب‌نشینی می‌تواند به تعویق یا حل‌کردن پنهانی تبدیل شود", action: "یک بازه کوتاه بی‌وظیفه برای مشاهده و استراحت بسازد" },
};
const RETROGRADE: Partial<Record<CanonicalPlanetId, { loop: string; tradeoff: string; action: string }>> = {
  mercury: { loop: "فکر پیش از بیان چند بار به درون برمی‌گردد", tradeoff: "ویرایش و بازنگری می‌تواند وضوح بسازد اما تصمیم را هم دیر کند", action: "نسخه موقت تصمیم را بنویسد و زمان بازبینی بعدی را مشخص کند" },
  venus: { loop: "ترجیح و ارزش بعد از جذب اولیه دوباره سنجیده می‌شود", tradeoff: "بازسنجی رابطه می‌تواند انتخاب را دقیق‌تر کند اما نارضایتی را هم دیرتر آشکار کند", action: "ترجیح و مرز را پیش از قطعی کردن انتخاب دوباره نام ببرد" },
  mars: { loop: "خواستن یا خشم پیش از اقدام یک دور درونی پیدا می‌کند", tradeoff: "مکث می‌تواند اقدام را دقیق‌تر کند اما انباشت خشم یا درخواست دیرهنگام بسازد", action: "خواسته را زودتر و در مقیاس کوچک بیان کند" },
  jupiter: { loop: "باور و امید پیش از گسترش دوباره از درون سنجیده می‌شود", tradeoff: "بازنگری معنا می‌تواند رشد را شخصی‌تر کند اما شروع‌های بزرگ را پراکنده کند", action: "یک باور را در عمل کوچک امتحان کند" },
  saturn: { loop: "مسئولیت و ترس بیشتر درونی می‌شوند و معیار سخت‌گیرانه‌تری می‌سازند", tradeoff: "خودنظارتی می‌تواند مهارت بسازد اما شروع را بی‌دلیل عقب بیندازد", action: "معیار کافی بودن و زمان پایان را از قبل تعیین کند" },
  uranus: { loop: "نیاز به آزادی ابتدا درون فعال می‌شود و بعد به تغییر بیرونی می‌رسد", tradeoff: "فاصله می‌تواند راه تازه نشان دهد اما قطع ناگهانی را هم وسوسه‌انگیز کند", action: "تغییر را با نسخه آزمایشی آغاز کند" },
  neptune: { loop: "دریافت و ابهام مدت بیشتری درون پردازش می‌شوند", tradeoff: "این مکث می‌تواند تخیل را غنی کند اما مرز واقعیت را مبهم‌تر کند", action: "برداشت را با شاهد بیرونی بررسی کند" },
  pluto: { loop: "کشمکش قدرت ابتدا درونی می‌شود و دیرتر به سطح می‌آید", tradeoff: "این عمق می‌تواند خودشناسی بسازد اما کنترل پنهان را طولانی کند", action: "ترس اصلی و بخش قابل کنترل را مستقیم نام ببرد" },
};

const PLANET_SIGN_BEHAVIOR_OVERRIDES: Partial<Record<string, { healthy: string; friction: string }>> = {
  "mercury:taurus": { healthy: "فکر آرام، ملموس و قابل پیگیری که پیش از نتیجه‌گیری به تجربه و زمان کافی تکیه می‌کند", friction: "دیر عوض کردن نتیجه یا نگه داشتن حرف تا زمانی که اطمینان کامل به دست بیاید" },
  "mars:taurus": { healthy: "اقدام پایدار، تحمل مسیر و توان ادامه دادن کاری که به نتیجه ملموس نیاز دارد", friction: "دیر شروع کردن، جمع شدن ناراحتی یا سخت تغییر دادن مسیر بعد از تصمیم" },
  "mars:libra": { healthy: "اقدامی که خواسته را روشن می‌کند و هم‌زمان اثر آن بر طرف مقابل را می‌سنجد", friction: "دیر گفتن خواسته، موافقت اولیه و جمع شدن دلخوری تا پیش از اقدام" },
  "moon:capricorn": { healthy: "امنیت عاطفی از راه ثبات، قابل اعتماد بودن و ساختن حمایت در عمل", friction: "پنهان کردن نیاز برای قوی ماندن یا تبدیل احساس به وظیفه پیش از تجربه کردن آن" },
  "moon:aquarius": { healthy: "فهم احساس با فاصله ذهنی کافی و بازگشت روشن به گفت‌وگو و درخواست حمایت", friction: "تحلیل احساس به جای تجربه آن یا دور شدن ناگهانی برای حفظ استقلال" },
  "venus:scorpio": { healthy: "نزدیکی عمیق، وفاداری و اعتمادی که از هماهنگی حرف و عمل ساخته می‌شود", friction: "آزمودن پنهانی، همه‌یا‌هیچ دیدن یا کنترل برای جلوگیری از آسیب‌پذیری" },
  "mercury:scorpio": { healthy: "فکری که دنبال علت پنهان می‌رود اما بعد از مشاهده، با سؤال مستقیم و شاهد واقعی نتیجه را می‌سنجد", friction: "قفل شدن روی یک تفسیر، نگه داشتن سؤال در ذهن و تبدیل ابهام به بدگمانی به‌جای پرسیدن مستقیم" },
  "mars:scorpio": { healthy: "اقدام حساب‌شده، استقامت و توان نگه داشتن نیرو تا زمانی که مرز و هدف روشن شود", friction: "نگه داشتن واکنش برای مدت طولانی، جمع شدن خشم یا رفتن به سمت کنترل و همه‌یا‌هیچ بعد از عبور از حد" },
  "mars:capricorn": { healthy: "اقدام منظم، تحمل مسیر و تبدیل فشار به نتیجه‌ای که زمان، معیار پایان و مسئولیتش روشن است", friction: "فشار برای نتیجه، سخت‌گیری با خود یا عقب انداختن شروع تا وقتی ساختار کاملاً آماده به نظر برسد" },
  "venus:aries": { healthy: "گفتن مستقیم ترجیح و خواسته، همراه با اجازه برای اینکه بعد از تجربه معیار ارزش را دوباره بسنجی", friction: "یکی گرفتن کشش یا ترجیح فوری با ارزش نهایی، پیش از اینکه ببینی این انتخاب با نیاز و سبک زندگی واقعی هماهنگ است یا نه" }
};
const PLANET_IDS = Object.keys(PLANETS) as CanonicalPlanetId[];
const SIGN_IDS = Object.keys(SIGNS) as CanonicalSignId[];
const HOUSE_IDS = Object.keys(HOUSES).map(Number) as CanonicalHouseNumber[];
export const PLANET_SIGN_INTERACTIONS = PLANET_IDS.flatMap((planetId, planetIndex) => SIGN_IDS.map((signId, signIndex) => { const planet = PLANETS[planetId]; const sign = SIGNS[signId]; const variant = (planetIndex * 3 + signIndex) % 4; const mechanism = [ `${planet.label} برای ${planet.function} از مسیر ${sign.method} حرکت می‌کند؛ ${planet.operation} باید با ${sign.priority} هماهنگ شود.`, `${sign.label} شکل کار ${planet.label} را عوض می‌کند: ${planet.operation} با ${sign.method} پیش می‌رود و معیار اصلی ${sign.priority} است.`, `در پیوند ${planet.label} و ${sign.label}، ${planet.function} فقط یک نیاز خام نمی‌ماند؛ از راه ${sign.method} به رفتار تبدیل می‌شود.`, `${planet.label} در ${sign.label} میان ${planet.function} و ${sign.priority} پل می‌زند؛ روش این پل ${sign.method} است.` ][variant]; return { key: `planet-sign:${planetId}:${signId}`, planetId, signId, mechanism, strength: `${planet.strength} وقتی با ${sign.strength} همراه شود.`, friction: `${planet.shadow}؛ به‌ویژه وقتی ${sign.shadow}`, action: `${planet.action} و ${sign.action}.` }; }));
for (const interaction of PLANET_SIGN_INTERACTIONS) {
  const override = PLANET_SIGN_BEHAVIOR_OVERRIDES[`${interaction.planetId}:${interaction.signId}`];
  if (override) {
    interaction.strength = override.healthy;
    interaction.friction = override.friction;
  }
}

export const PLANET_HOUSE_INTERACTIONS = PLANET_IDS.flatMap((planetId, planetIndex) => HOUSE_IDS.map((houseNumber, houseIndex) => { const planet = PLANETS[planetId]; const house = HOUSES[houseNumber]; const variant = (planetIndex + houseIndex * 2) % 3; const context = [ `${planet.label} در خانه ${houseNumber.toLocaleString("fa-IR")} ${planet.operation} را وارد میدان ${house.field} می‌کند.`, `خانه ${houseNumber.toLocaleString("fa-IR")} برای ${planet.label} جایی است که ${planet.function} باید در ${house.field} شکل عملی پیدا کند.`, `وقتی ${planet.label} به خانه ${houseNumber.toLocaleString("fa-IR")} می‌رسد، ${house.field} تبدیل به صحنه اصلی ${planet.function} می‌شود.` ][variant]; return { key: `planet-house:${planetId}:${houseNumber}`, planetId, houseNumber, context, everyday: `${house.scene}، نیاز ${planet.label} معمولاً زودتر قابل مشاهده می‌شود.`, strength: `${planet.strength} می‌تواند ${house.outcome}.`, friction: `${planet.shadow} می‌تواند در این میدان با این ریسک روبه‌رو شود که ${house.shadow}` }; }));
export const SIGN_HOUSE_INTERACTIONS = SIGN_IDS.flatMap((signId, signIndex) => HOUSE_IDS.map((houseNumber, houseIndex) => { const sign = SIGNS[signId]; const house = HOUSES[houseNumber]; const variant = (signIndex * 5 + houseIndex) % 3; const context = [ `${sign.label} در خانه ${houseNumber.toLocaleString("fa-IR")} میدان ${house.field} را با ${sign.method} تجربه می‌کند.`, `در خانه ${houseNumber.toLocaleString("fa-IR")}، کیفیت ${sign.label} باعث می‌شود ${house.field} بیشتر از مسیر ${sign.priority} فهمیده شود.`, `پیوند ${sign.label} با خانه ${houseNumber.toLocaleString("fa-IR")} یعنی ${house.field} با روش ${sign.method} شکل می‌گیرد.` ][variant]; return { key: `sign-house:${signId}:${houseNumber}`, signId, houseNumber, context, strength: `${sign.strength} کمک می‌کند این خانه ${house.outcome}.`, friction: `${sign.shadow} و در این خانه ${house.shadow}`, action: `${sign.action} و ${house.action}.` }; }));
const TARGETED: Partial<Record<string, Omit<CanonicalPlacementNarrative, "semanticKey" | "specificity" | "facts" | "contextExpression" | "focus">>> = {
  "sun:aquarius:5": { thesis: "خورشید در دلو و خانه ۵ هویت را به خلاقیتی وصل می‌کند که باید هم شخصی باشد و هم متفاوت؛ دیده‌شدن وقتی رضایت‌بخش است که نتیجه واقعاً امضای خودت را داشته باشد، نه فقط واکنش دیگران را.", mechanism: "دلو فاصله لازم برای دیدن راه تازه را می‌دهد و خانه ۵ آن ایده را مجبور می‌کند به چیزی شخصی و قابل مشاهده تبدیل شود؛ بنابراین استقلال فکری فقط وقتی کامل می‌شود که از مرحله ایده عبور کند.", everydayScene: "ممکن است برای یک پروژه، رابطه یا سرگرمی ناگهان راهی پیدا کنی که دیگران به آن فکر نکرده‌اند و بعد بیشترین انرژی را زمانی بگیری که همان تفاوت را به خروجی واقعی تبدیل کنی.", constructiveExpression: "توان اصلی، ساختن چیزی تازه بدون تقلید از فرم آماده و اجازه دادن به سلیقه شخصی برای هدایت انتخاب است.", frictionExpression: "اگر تازگی از پایان مهم‌تر شود، پروژه می‌تواند بعد از موج اولیه هیجان رها شود یا فاصله از تأیید دیگران به فاصله از بازخورد مفید تبدیل شود.", actionCue: "یک ایده متفاوت را در نسخه‌ای کوچک تمام کن و فقط بعد از پایان تصمیم بگیر چقدر باید تغییرش بدهی." },
  "mercury:aquarius:5": { thesis: "عطارد در دلو و خانه ۵ ذهن را از مسیر معمول بیرون می‌برد و بعد از آن انتظار خروجی دارد؛ ایده وقتی زنده می‌شود که بتواند به زبان، طرح، شوخی، محصول یا شکل خلاق دیگری تبدیل شود.", mechanism: "عطارد پیوندها را سریع می‌بیند، دلو الگوهای نامعمول را برجسته می‌کند و خانه ۵ از این ترکیب بیان شخصی می‌خواهد؛ برای همین فکر فقط جمع‌آوری اطلاعات نیست، نوعی ساختن است.", everydayScene: "در گفت‌وگو یا کار خلاق ممکن است چند مفهوم دور را ناگهان به هم وصل کنی و چیزی بگویی یا بسازی که برای بقیه غیرمنتظره اما منطقی به نظر برسد.", constructiveExpression: "اصالت فکری، سرعت دیدن رابطه‌ها و توان تبدیل ایده پیچیده به فرم شخصی از ظرفیت‌های قوی این جایگاه‌اند.", frictionExpression: "تازگی می‌تواند ایده بعدی را زودتر از پایان ایده فعلی جذاب کند یا توضیح روشن را فدای جهش ذهنی کند.", actionCue: "یکی از ایده‌های غیرمعمول را انتخاب کن و قبل از باز کردن شاخه بعدی، آن را به یک خروجی قابل نشان دادن برسان." },
  "venus:aquarius:5": { thesis: "زهره در دلو و خانه ۵ لذت و کشش را با آزادی، دوستی و بیان متفاوت گره می‌زند؛ جذابیت وقتی بیشتر می‌شود که رابطه یا کار خلاق جا برای فردیت واقعی داشته باشد.", mechanism: "زهره می‌خواهد ارزش و نزدیکی را تجربه کند، دلو از قالب اجباری فاصله می‌گیرد و خانه ۵ میل به انتخاب شخصی را پررنگ می‌کند؛ در نتیجه صمیمیت سالم به فضای تنفس نیاز دارد.", everydayScene: "ممکن است به آدم، هنر یا تجربه‌ای جذب شوی که چیزی تازه در تو باز می‌کند و در رابطه از این‌که هر دو نفر علایق و جهان شخصی خودشان را داشته باشند انرژی بگیری.", constructiveExpression: "دوستی در دل رابطه، پذیرش تفاوت و جسارت انتخاب سلیقه شخصی می‌تواند نزدیکی را زنده نگه دارد.", frictionExpression: "فاصله برای حفظ آزادی ممکن است نارضایتی یا نیاز عاطفی را دیرتر قابل گفتن کند، یا تازگی بیش از عمق ارزش پیدا کند.", actionCue: "در یک رابطه یا انتخاب خلاق، هم چیزی که آزادی می‌دهد و هم چیزی که تعهد می‌خواهد صریح نام ببر." },
  "jupiter:aquarius:5": { thesis: "مشتری در دلو و خانه ۵ رشد را از راه آزمایش خلاق، شبکه ایده‌ها و اجازه دادن به خود برای بزرگ‌تر فکر کردن دنبال می‌کند؛ فرصت وقتی واقعی می‌شود که ایده به تجربه تبدیل شود.", mechanism: "مشتری افق را باز می‌کند، دلو امکان متفاوت را می‌بیند و خانه ۵ می‌خواهد آن امکان با امضای شخصی ساخته شود؛ به همین دلیل خلاقیت می‌تواند موتور رشد باشد.", everydayScene: "ممکن است یک ایده جانبی، پروژه شخصی یا همکاری خلاق ناگهان به دریچه‌ای بزرگ‌تر تبدیل شود و تو را به آدم‌ها یا تجربه‌های تازه وصل کند.", constructiveExpression: "خوش‌بینی خلاق، جرئت امتحان راه تازه و توان الهام دادن به دیگران از نقاط قوت این ترکیب است.", frictionExpression: "بزرگ دیدن می‌تواند تعداد پروژه‌ها را از ظرفیت بیشتر کند یا هیجان امکان تازه را جای پیگیری جزئیات بنشاند.", actionCue: "از میان ایده‌های بزرگ فقط یک نسخه کوچک را انتخاب کن و تا نتیجه قابل مشاهده جلو ببر." },
  "uranus:aquarius:5": { thesis: "اورانوس در دلو و خانه ۵ آزادی و خلاقیت را در یک نقطه جمع می‌کند؛ بیان شخصی برای زنده ماندن نیاز دارد امکان شکستن فرم و ساختن راه تازه را حفظ کند.", mechanism: "اورانوس تغییر الگو را می‌خواهد، دلو این میل را طبیعی‌تر می‌کند و خانه ۵ آن را شخصی و قابل دیدن می‌سازد؛ نتیجه می‌تواند نوآوری واقعی باشد، نه صرفاً مخالفت با قالب.", everydayScene: "ممکن است وسط یک پروژه ناگهان ساختار کاملاً تازه‌ای ببینی یا در عشق و سرگرمی از تکرار سریع خسته شوی و نیاز به شکل متفاوتی از تجربه پیدا کنی.", constructiveExpression: "نوآوری، استقلال در سلیقه و توان ساختن چیزی که قبلاً قالب آماده‌ای برایش نبوده ظرفیت اصلی این جایگاه است.", frictionExpression: "اگر تغییر خودش هدف شود، ادامه دادن بخش‌های کم‌هیجان یا حفظ پیوند بعد از فروکش تازگی دشوار می‌شود.", actionCue: "قبل از عوض کردن کامل مسیر، فقط یک جزء را تغییر بده و اثرش را روی کل تجربه ببین." },
  "moon:taurus:8": { thesis: "ماه در ثور و خانه ۸ امنیت را در جایی می‌خواهد که کنترل کامل ممکن نیست؛ برای همین اعتماد باید در زمان، رفتار ثابت و نشانه‌های ملموس ساخته شود تا بدن هم چیزی را که ذهن می‌داند باور کند.", mechanism: "ماه به امنیت نیاز دارد، ثور آن را از راه ثبات و لمس واقعیت می‌سنجد و خانه ۸ موضوع را وارد صمیمیت و منابع مشترک می‌کند؛ نتیجه نیاز به اعتماد آهسته اما عمیق است.", everydayScene: "ممکن است از نظر منطقی بدانی رابطه یا توافق امن است اما برای رها کردن احتیاط به تکرار رفتار قابل اعتماد نیاز داشته باشی، یا جدا شدن از چیزی آشنا بیش از انتظار زمان ببرد.", constructiveExpression: "وفاداری، تحمل فرایند و توان ساختن امنیت واقعی در صمیمیت از ظرفیت‌های قوی این ترکیب است.", frictionExpression: "امنیت آشنا می‌تواند حتی بعد از کم شدن رضایت نگهت دارد، یا ترس از آسیب‌پذیری باز شدن و تقسیم کنترل را دیر کند.", actionCue: "به‌جای قول بزرگ، یک رفتار کوچک و تکرارشونده را به‌عنوان معیار اعتماد انتخاب کن." },
  "mars:libra:1": { thesis: "مریخ در میزان و خانه ۱ اقدام را از همان ابتدا رابطه‌ای می‌کند: خواسته شخصی وجود دارد، اما پیش از بیرون آمدن واکنش طرف مقابل را هم می‌سنجد؛ هنر این جایگاه، تبدیل ملاحظه به مذاکره است نه حذف خود.", mechanism: "مریخ می‌خواهد حرکت کند، میزان پیامد رابطه‌ای حرکت را می‌بیند و خانه ۱ تصمیم را به حضور و مرز شخصی وصل می‌کند؛ بنابراین اقدام مؤثر نیاز دارد خواسته زودتر از دلخوری بیان شود.", everydayScene: "در یک اختلاف ممکن است اول راه میانه را پیشنهاد بدهی و چند ساعت بعد بفهمی بخشی از خواسته خودت اصلاً گفته نشده؛ اگر زودتر آن را نام ببری، مذاکره واقعی‌تر می‌شود.", constructiveExpression: "جرئت همراه با انصاف، توان مذاکره زیر فشار و دفاع از مرزی که لزوماً به حمله تبدیل نمی‌شود از قوت‌های این ترکیب است.", frictionExpression: "سنجیدن واکنش دیگری می‌تواند اقدام را دیر کند و خشم جمع‌شده ناگهان لحن یا تصمیم را تندتر از نیاز واقعی کند.", actionCue: "پیش از موافقت، خواسته خودت را در یک جمله روشن بگو و بعد وارد مذاکره شو." },
  "saturn:aries:7": { thesis: "زحل در حمل و خانه ۷ رابطه را به جایی تبدیل می‌کند که استقلال باید شکل قابل اتکا پیدا کند؛ گفتن «من این را می‌خواهم» کافی نیست، انتخاب باید بتواند مذاکره، پیامد و زمان را هم تحمل کند.", mechanism: "زحل ساختار می‌خواهد، حمل شروع و استقلال را جلو می‌آورد و خانه ۷ هر تصمیم را مقابل واقعیت دیگری می‌گذارد؛ نتیجه درس مداوم درباره مرز، تعهد و مسئولیت انتخاب است.", everydayScene: "در رابطه یا قرارداد ممکن است هم از محدود شدن حساس شوی و هم از بی‌قاب بودن طرف مقابل خسته؛ بهترین حالت وقتی شکل می‌گیرد که آزادی هر دو نفر قواعد روشن و قابل پیگیری داشته باشد.", constructiveExpression: "توان ساختن تعهدی که استقلال را نمی‌بلعد و مرزی که با زمان قابل اعتماد می‌شود ظرفیت مهم این جایگاه است.", frictionExpression: "ترس از وابستگی یا اشتباه می‌تواند شروع تعهد را عقب بیندازد، و در سوی دیگر واکنش سریع برای حفظ استقلال می‌تواند گفت‌وگو را سخت کند.", actionCue: "در یک رابطه یا همکاری، یک حق شخصی و یک مسئولیت متقابل را واضح و قابل سنجش تعریف کن." },
};
function isPlanetId(value: string): value is CanonicalPlanetId { return Object.prototype.hasOwnProperty.call(PLANETS, value); }
function isSignId(value: string): value is CanonicalSignId { return Object.prototype.hasOwnProperty.call(SIGNS, value); }
function isHouse(value: number | null | undefined): value is CanonicalHouseNumber { return Number.isInteger(value) && Number(value) >= 1 && Number(value) <= 12; }
function stableVariant(planetId: CanonicalPlanetId, signId: CanonicalSignId, houseNumber: CanonicalHouseNumber) { return (PLANET_IDS.indexOf(planetId) * 17 + SIGN_IDS.indexOf(signId) * 7 + houseNumber) % 6; }
function lowerFirst(value: string) { return value.length ? value[0]!.toLocaleLowerCase("fa-IR") + value.slice(1) : value; }
function toObservedOperation(value: string) { return value.replace(/کند(?=\s|$)/gu, "می‌کند").replace(/دهد(?=\s|$)/gu, "می‌دهد"); }
export function buildCanonicalPlacementNarrative(input: { planetId: string; signId: string; houseNumber?: number | null; retrograde?: boolean; audienceMode?: CanonicalAudienceMode; }): CanonicalPlacementNarrative | null {
  if (!isPlanetId(input.planetId) || !isSignId(input.signId) || !isHouse(input.houseNumber)) return null;
  const planetId = input.planetId; const signId = input.signId; const houseNumber = input.houseNumber; const planet = PLANETS[planetId]; const sign = SIGNS[signId]; const house = HOUSES[houseNumber];
  const ps = PLANET_SIGN_INTERACTIONS.find((item) => item.planetId === planetId && item.signId === signId)!; const ph = PLANET_HOUSE_INTERACTIONS.find((item) => item.planetId === planetId && item.houseNumber === houseNumber)!; const sh = SIGN_HOUSE_INTERACTIONS.find((item) => item.signId === signId && item.houseNumber === houseNumber)!;
  const key = `${planetId}:${signId}:${houseNumber}`; const targeted = input.audienceMode === "caregiver" ? undefined : TARGETED[key]; const variant = stableVariant(planetId, signId, houseNumber);
  const theses = [ `${planet.label} در ${sign.label} و خانه ${houseNumber.toLocaleString("fa-IR")} کارکرد ${planet.function} را در میدان ${house.field} با ریتم ${sign.method} پیش می‌برد؛ نیاز سیاره و زمینه خانه در یک مسئله واحد جمع می‌شوند.`, `در خانه ${houseNumber.toLocaleString("fa-IR")}، ${planet.label} در ${sign.label} مجبور است ${planet.function} را به تجربه‌ای واقعی در ${house.field} تبدیل کند؛ روش این کار ${sign.method} است.`, `${planet.label} وقتی در ${sign.label} و خانه ${houseNumber.toLocaleString("fa-IR")} قرار می‌گیرد، ${sign.priority} را وارد ${house.field} می‌کند و ${planet.function} از همین‌جا شکل رفتاری می‌گیرد.`, `پیوند ${planet.label}، ${sign.label} و خانه ${houseNumber.toLocaleString("fa-IR")} یک محور روشن می‌سازد: ${planet.operation} در ${house.field} باید با ${sign.priority} سازگار شود.`, `${house.field} برای این جایگاه صحنه اصلی است: ${planet.label} در ${sign.label} ${planet.function} را با ${sign.method} وارد خانه ${houseNumber.toLocaleString("fa-IR")} می‌کند.`, `این جایگاه از ترکیب سه عامل ساخته می‌شود: ${planet.label} در ${sign.label}، خانه ${houseNumber.toLocaleString("fa-IR")} و نیاز به ${planet.function}؛ نتیجه در ${house.field} خودش را نشان می‌دهد.` ];
  let thesis = targeted?.thesis ?? theses[variant]; let mechanism = targeted?.mechanism ?? `${ps.mechanism} ${ph.context} ${sh.context}`; let everydayScene = targeted?.everydayScene ?? `${house.scene}، ${planet.label} ${toObservedOperation(planet.operation)} و این حرکت بیشتر با ریتم ${sign.method} دیده می‌شود.`; const constructiveExpression = targeted?.constructiveExpression ?? `${ps.strength} ${ph.strength} ${sh.strength}`; let frictionExpression = targeted?.frictionExpression ?? `${ps.friction}؛ ${ph.friction}`; let actionCue = targeted?.actionCue ?? `${planet.action}؛ ${sign.action}؛ ${house.action}.`;
  const actualRetrograde = Boolean(input.retrograde && planetId !== "sun" && planetId !== "moon" && RETROGRADE[planetId]); if (actualRetrograde) { const retro = RETROGRADE[planetId]!; thesis = `با پس‌روی ${planet.label}، ${lowerFirst(thesis)} در عمل یک مرحله درونی هم پیدا می‌کند: ${retro.loop}.`; mechanism = `${retro.loop}. این بازگشت درونی در ${house.field} با روش ${sign.method} پردازش می‌شود و بعد به رفتار بیرونی می‌رسد.`; everydayScene = `${house.scene}، ممکن است پاسخ بیرونی کمی دیرتر برسد چون ${retro.loop}.`; frictionExpression = `${retro.tradeoff}. در ${house.field}، ${sign.shadow}`; actionCue = retro.action + "."; }
  if (input.audienceMode === "caregiver") { thesis = `برای همراه بزرگسال، ${thesis}`; everydayScene = `در رفتار روزمره کودک، ${everydayScene}`; actionCue = `کمک کنید کودک ${lowerFirst(actionCue)}`; }
  return { semanticKey: `placement:${key}${actualRetrograde ? ":retrograde" : ""}`, thesis, mechanism, contextExpression: `${ph.context} ${sh.context}`, everydayScene, constructiveExpression, frictionExpression, focus: `${planet.function} در ${house.field}`, actionCue, specificity: targeted ? "targeted" : "matrix-composed", facts: { planetId, signId, houseNumber, retrograde: actualRetrograde, sourceRefs: [`placement:${planetId}`, `sign:${signId}`, `house:${houseNumber}`] } };
}
export function buildCanonicalHouseNarrative(input: { houseNumber: number; members: Array<{ planetId: string; signId: string; retrograde?: boolean }>; audienceMode?: CanonicalAudienceMode; }): CanonicalHouseNarrative | null {
  if (!isHouse(input.houseNumber)) return null;
  const houseNumber = input.houseNumber;
  const house = HOUSES[houseNumber];
  const units = input.members
    .map((member) => buildCanonicalPlacementNarrative({ ...member, houseNumber, audienceMode: input.audienceMode }))
    .filter((unit): unit is CanonicalPlacementNarrative => Boolean(unit));
  if (units.length === 0) return null;
  const labels = units.slice(0, 3).map((unit) => `${PLANETS[unit.facts.planetId].label} در ${SIGNS[unit.facts.signId].label}`);
  const functions = units.slice(0, 3).map((unit) => PLANETS[unit.facts.planetId].function);
  const methods = Array.from(new Set(units.slice(0, 3).map((unit) => SIGNS[unit.facts.signId].method)));
  const integrationLines = [
    `در خانه اول، حضور و شروع باید میان این کارکردها سهم‌بندی شود`,
    `در خانه دوم، ارزش و منابع وقتی روشن‌تر می‌شوند که هر نیاز جای خودش را پیدا کند`,
    `در خانه سوم، فکر و ارتباط باید این نیروها را به زبان قابل پاسخ تبدیل کنند`,
    `در خانه چهارم، امنیت و ریشه‌ها نیاز دارند این کارکردها بدون حذف هم تنظیم شوند`,
    `در خانه پنجم، بیان شخصی وقتی زنده می‌ماند که این نیروها به یک خروجی واقعی برسند`,
    `در خانه ششم، ریتم روزانه باید میان این نیازها شکل عملی و قابل تکرار بسازد`,
    `در خانه هفتم، رابطه و شراکت از این نیروها مذاکره و مرز روشن می‌خواهند`,
    `در خانه هشتم، اعتماد و صمیمیت وقتی پخته‌تر می‌شوند که این نیازها سهم خود را آشکار کنند`,
    `در خانه نهم، معنا و افق تازه باید این کارکردها را به تجربه‌ای قابل آزمون وصل کنند`,
    `در خانه دهم، نقش و مسئولیت زمانی منسجم‌تر می‌شوند که این نیروها جهت مشترک پیدا کنند`,
    `در خانه یازدهم، جمع و آینده به این نیروها نیاز دارند تا فردیت و همکاری را کنار هم نگه دارند`,
    `در خانه دوازدهم، خلوت و پشت‌صحنه جایی است که این کارکردها باید پیش از بیرون‌آمدن تنظیم شوند`,
  ] as const;
  const pressureLines = [
    `فشار این حوزه می‌تواند اقدام شخصی و واکنش به محیط را هم‌زمان وارد تصمیم کند`,
    `در تنش، امنیت مادی و ارزش شخصی ممکن است جهت‌های متفاوتی بخواهند`,
    `وقتی ارتباط سخت می‌شود، چند برداشت می‌توانند هم‌زمان برای پاسخ جلو بیایند`,
    `زیر فشار، نیاز به امنیت و عادت‌های قدیمی ممکن است یکدیگر را تقویت یا محدود کنند`,
    `در اصطکاک، میل به دیده‌شدن و نیاز به رضایت شخصی ممکن است یک اندازه نباشند`,
    `وقتی ریتم روزانه فشرده می‌شود، وظیفه و نیاز شخصی ممکن است بر سر اولویت رقابت کنند`,
    `در اختلاف، حفظ پیوند و حفظ مرز شخصی ممکن است پاسخ یکسانی نخواهند`,
    `وقتی اعتماد حساس می‌شود، میل به نزدیکی و نیاز به کنترل ممکن است هم‌زمان فعال شوند`,
    `در فشار فکری، باور قبلی و تجربه تازه می‌توانند جهت‌های متفاوتی پیشنهاد کنند`,
    `وقتی مسئولیت سنگین می‌شود، خواست شخصی و انتظار بیرونی ممکن است هم‌زمان سهم بخواهند`,
    `در جمع، تعلق و استقلال ممکن است برای یک تصمیم واحد وزن‌های متفاوتی داشته باشند`,
    `در دوره‌های مبهم، نیاز به عقب‌نشینی و نیاز به عمل ممکن است هم‌زمان حضور داشته باشند`,
  ] as const;
  const index = houseNumber - 1;
  const thesis = `خانه ${houseNumber.toLocaleString("fa-IR")} در این چارت با ${labels.join("، ")} به یک میدان فعال تبدیل می‌شود؛ ${house.field} جایی است که ${functions.join("، ")} به هم می‌رسند. ${integrationLines[index]}.`;
  const synthesis = `ریتم غالب ${methods.join(" و ")} است و نتیجه وقتی پخته‌تر می‌شود که این حوزه ${house.outcome}.`;
  const constructiveExpression = `${units.slice(0, 2).map((unit) => unit.constructiveExpression).join(" ")} این ظرفیت‌ها در خانه ${houseNumber.toLocaleString("fa-IR")} به یک موضوع مشترک وصل می‌شوند.`;
  const frictionExpression = `${pressureLines[index]}؛ ${house.shadow} و ${units[0]!.frictionExpression}`;
  const everydayScene = `${house.scene}، معمولاً یک انگیزه تنها نیست؛ انتخاب اینجا می‌تواند هم‌زمان روی چند بخش تجربه اثر بگذارد.`;
  const actionCue = `${house.action} سپس فقط یک خواسته اصلی را برای همان موقعیت نام ببر.`;
  return { semanticKey: `house:${houseNumber}:canonical:${units.map((unit) => unit.facts.planetId).join("-")}`, thesis, synthesis, everydayScene, constructiveExpression, frictionExpression, actionCue, memberSemanticKeys: units.map((unit) => unit.semanticKey) };
}
export const ASCENDANT_SIGN_SEMANTICS: Record<CanonicalSignId, { thesis: string; dailyLifeExample: string; healthyExpression: string; possibleFriction: string; smallExperiment: string }> = {
  aries: { thesis: "رایزینگ حمل حضور اولیه را سریع، مستقیم و آماده شروع نشان می‌دهد", dailyLifeExample: "در ورود به جمع یا کار تازه معمولاً پیش از دیگران حرکت را آغاز می‌کنی", healthyExpression: "جرئت شروع و واکنش روشن", possibleFriction: "عجله یا دفاع پیش از شنیدن موقعیت", smallExperiment: "پیش از شروع یک مکث کوتاه برای تعیین هدف بگذار" },
  taurus: { thesis: "رایزینگ ثور حضور اولیه را آرام، ثابت و قابل اتکا می‌کند", dailyLifeExample: "در موقعیت تازه معمولاً اول فضا را می‌سنجی و بعد با ریتم خودت جلو می‌روی", healthyExpression: "آرامش و ثبات بیرونی", possibleFriction: "کند شدن تغییر فقط چون ریتم آشنا امن‌تر است", smallExperiment: "یک تغییر کوچک را بدون به‌هم‌زدن کل ریتم امتحان کن" },
  gemini: { thesis: "رایزینگ جوزا حضور اولیه را کنجکاو، کلامی و واکنش‌پذیر می‌کند", dailyLifeExample: "در جمع تازه معمولاً با سؤال یا گفت‌وگو راه ورود پیدا می‌کنی", healthyExpression: "چابکی ارتباطی", possibleFriction: "پراکنده شدن میان چند برداشت اولیه", smallExperiment: "بعد از جمع‌کردن اطلاعات یک موضع موقت انتخاب کن" },
  cancer: { thesis: "رایزینگ سرطان حضور اولیه را حساس به فضا، تعلق و امنیت می‌کند", dailyLifeExample: "در موقعیت تازه زود متوجه حال جمع و میزان امن بودن آن می‌شوی", healthyExpression: "مراقبت و خواندن فضا", possibleFriction: "دفاع یا عقب‌نشینی پیش از بیان نیاز", smallExperiment: "نیاز خودت را همراه با برداشتت از فضا نام ببر" },
  leo: { thesis: "رایزینگ اسد حضور اولیه را گرم، قابل مشاهده و شخصی می‌کند", dailyLifeExample: "در جمع تازه معمولاً حضورت سریع دیده می‌شود یا مسئولیت دیده‌شدن را می‌پذیری", healthyExpression: "اعتماد به خودابرازی", possibleFriction: "وابسته شدن به واکنش و تأیید بیرونی", smallExperiment: "یک انتخاب را حتی بدون بازخورد فوری ادامه بده" },
  virgo: { thesis: "رایزینگ سنبله حضور اولیه را دقیق، مشاهده‌گر و مسئله‌محور می‌کند", dailyLifeExample: "در موقعیت تازه زود جزئیات، نقص یا کاری را که باید انجام شود می‌بینی", healthyExpression: "دقت و مفید بودن", possibleFriction: "خودانتقادی یا دیر وارد شدن به‌خاطر کامل نبودن", smallExperiment: "با نسخه کافی وارد شو و اصلاح را بعداً انجام بده" },
  libra: { thesis: "رایزینگ میزان حضور اولیه را رابطه‌محور، مؤدب و تنظیم‌گر می‌کند", dailyLifeExample: "در جمع تازه زود واکنش دیگران و تعادل میان آدم‌ها را می‌سنجی", healthyExpression: "مذاکره و ساختن فضای متعادل", possibleFriction: "دیر شنیدن خواسته خودت", smallExperiment: "قبل از سازگار شدن یک ترجیح شخصی را نام ببر" },
  scorpio: { thesis: "رایزینگ عقرب حضور اولیه را متمرکز، محتاط و حساس به قدرت و اعتماد می‌کند", dailyLifeExample: "در موقعیت تازه معمولاً پیش از باز شدن، نیت و ثبات رفتار دیگران را می‌سنجی", healthyExpression: "تمرکز و تشخیص عمق", possibleFriction: "محافظه‌کاری یا آزمون پنهانی", smallExperiment: "یک نگرانی را مستقیم و بدون آزمون بیان کن" },
  sagittarius: { thesis: "رایزینگ قوس حضور اولیه را باز، صریح و رو به تجربه می‌کند", dailyLifeExample: "در محیط تازه معمولاً با حرکت، شوخی یا دیدن امکان بزرگ‌تر وارد می‌شوی", healthyExpression: "خوش‌بینی و جسارت تجربه", possibleFriction: "قول یا نتیجه‌گیری سریع‌تر از داده", smallExperiment: "یک برداشت بزرگ را با جزئیات واقعی چک کن" },
  capricorn: { thesis: "رایزینگ جدی حضور اولیه را جدی، هدفمند و مسئول نشان می‌دهد", dailyLifeExample: "در موقعیت تازه معمولاً نقش، انتظار و نتیجه را زود می‌سنجی", healthyExpression: "قابلیت اتکا و کنترل ریتم", possibleFriction: "سخت‌گیری و دیر نشان دادن بخش نرم‌تر", smallExperiment: "پیش از اثبات توانمندی یک نیاز ساده را هم بیان کن" },
  aquarius: { thesis: "رایزینگ دلو حضور اولیه را مستقل، متفاوت و الگو‌بین می‌کند", dailyLifeExample: "در جمع تازه معمولاً اول ساختار و فاصله مناسب خودت را پیدا می‌کنی", healthyExpression: "اصالت و دیدن راه تازه", possibleFriction: "فاصله گرفتن پیش از ساختن ارتباط", smallExperiment: "یک نظر متفاوت را همراه با یک نقطه اتصال انسانی بیان کن" },
  pisces: { thesis: "رایزینگ حوت حضور اولیه را نرم، دریافت‌گر و حساس به حال فضا می‌کند", dailyLifeExample: "در محیط تازه ممکن است پیش از موضع‌گیری، حال و نیاز دیگران را جذب کنی", healthyExpression: "انعطاف و همدلی", possibleFriction: "مرز مبهم یا تغییر موضع با فضای جمع", smallExperiment: "پیش از سازگار شدن احساس و خواسته خودت را جداگانه نام ببر" },
};
export function buildAscendantSignNarrative(signId: string) { if (!isSignId(signId)) return null; const item = ASCENDANT_SIGN_SEMANTICS[signId]; return { plainMeaning: item.thesis, dailyLifeExample: item.dailyLifeExample, healthyExpression: item.healthyExpression, possibleFriction: item.possibleFriction, focus: `شروع، حضور و تصویر اولیه با ریتم ${SIGNS[signId].label}`, smallExperiment: item.smallExperiment, symbolicBody: "", semanticKey: `ascendant:${signId}`, mechanism: `${SIGNS[signId].method} شیوه ورود اولیه به موقعیت را شکل می‌دهد.`, contextExpression: `خانه ۱ و رایزینگ این کیفیت را در بدن، شروع و تصویر اولیه قابل دیدن می‌کنند.` }; }
export const NODE_SIGN_AXIS_SEMANTICS: Record<CanonicalSignId, { thesis: string; bridge: string }> = {
  aries: { thesis: "حرکت از سنجیدن بیش از حد دیگری به انتخاب و اقدام شخصی", bridge: "مهارت رابطه و دیدن دو طرف حفظ می‌شود، اما رشد نیاز دارد خواست خودت زودتر وارد تصمیم شود" },
  taurus: { thesis: "حرکت از شدت و کنترل به ثبات، ارزش و امنیت ملموس", bridge: "توان دیدن عمق حفظ می‌شود، اما رشد با ساده‌کردن و ساختن چیزی پایدار پیش می‌رود" },
  gemini: { thesis: "حرکت از پاسخ بزرگ و باور قطعی به پرسش، مشاهده و گفت‌وگوی نزدیک", bridge: "دیدن تصویر بزرگ می‌ماند، اما رشد از کنجکاوی و اصلاح نظر با داده تازه می‌آید" },
  cancer: { thesis: "حرکت از کنترل و عملکرد به مراقبت، تعلق و امنیت درونی", bridge: "توان مسئولیت‌پذیری حفظ می‌شود، اما رشد نیاز دارد نیاز عاطفی هم جدی گرفته شود" },
  leo: { thesis: "حرکت از فاصله جمعی به حضور شخصی و خلاقیت قابل دیدن", bridge: "دیدن جمع و آینده حفظ می‌شود، اما رشد با پذیرفتن سهم و میل شخصی پررنگ‌تر می‌شود" },
  virgo: { thesis: "حرکت از حل‌شدن در امکان‌ها به تشخیص، نظم و اقدام قابل سنجش", bridge: "حساسیت و تخیل حفظ می‌شود، اما رشد با تبدیل آن به جزئیات عملی شکل می‌گیرد" },
  libra: { thesis: "حرکت از خودبسندگی واکنشی به مذاکره، همکاری و دیدن دو طرف", bridge: "جرئت شروع حفظ می‌شود، اما رشد با ساختن توافقی رخ می‌دهد که دیگری هم در آن واقعی است" },
  scorpio: { thesis: "حرکت از کنترل منابع شخصی به اعتماد، عمق و سهم مشترک", bridge: "ثبات و خوداتکایی حفظ می‌شود، اما رشد با پذیرفتن آسیب‌پذیری و تغییر مشترک می‌آید" },
  sagittarius: { thesis: "حرکت از اطلاعات پراکنده به معنا، موضع و افق شخصی", bridge: "پرسشگری حفظ می‌شود، اما رشد با انتخاب یک جهت و آزمودن آن در تجربه شکل می‌گیرد" },
  capricorn: { thesis: "حرکت از امنیت خصوصی به مسئولیت، ساختار و اثر بیرونی", bridge: "مراقبت و تعلق حفظ می‌شود، اما رشد با پذیرفتن نقش و نتیجه قابل اتکا پیش می‌رود" },
  aquarius: { thesis: "حرکت از نیاز به مرکز بودن به همکاری، فاصله ذهنی و آینده مشترک", bridge: "خودابرازی حفظ می‌شود، اما رشد وقتی کامل‌تر است که سهم شخصی وارد شبکه‌ای بزرگ‌تر شود" },
  pisces: { thesis: "حرکت از کنترل جزئیات به اعتماد، دریافت و انعطاف", bridge: "تشخیص و مهارت عملی حفظ می‌شود، اما رشد نیاز دارد بخشی از ابهام بدون کنترل کامل تحمل شود" },
};
export const NODE_HOUSE_AXIS_SEMANTICS: Record<CanonicalHouseNumber, { thesis: string; bridge: string }> = {
  1: { thesis: "حرکت از تعریف خود با پاسخ دیگری به حضور و انتخاب شخصی", bridge: "تمرین رشد این محور، نشان دادن خواسته و قبول مسئولیت انتخاب خود است" },
  2: { thesis: "حرکت از وابستگی به منابع مشترک به ساختن ارزش و امنیت شخصی", bridge: "تمرین رشد، روشن کردن معیار ارزش و چیزی است که واقعاً در اختیار خودت قرار دارد" },
  3: { thesis: "حرکت از پاسخ‌های بزرگ به مشاهده، سؤال و ارتباط روزمره", bridge: "تمرین رشد، ساده گفتن و اجازه دادن به داده تازه برای اصلاح نظر است" },
  4: { thesis: "حرکت از نتیجه و نقش بیرونی به ریشه، خانه و امنیت درونی", bridge: "تمرین رشد، جدی گرفتن نیاز خصوصی به اندازه مسئولیت اجتماعی است" },
  5: { thesis: "حرکت از نقش جمعی به میل، خلاقیت و امضای شخصی", bridge: "تمرین رشد، ساختن چیزی است که انتخاب و لذت شخصی در آن قابل دیدن باشد" },
  6: { thesis: "حرکت از خلوت و نیت پنهان به نظم، بدن و کار روزمره", bridge: "تمرین رشد، تبدیل الهام به کاری کوچک و تکرارشونده است" },
  7: { thesis: "حرکت از خودبسندگی به همکاری، درخواست و وابستگی سالم", bridge: "تمرین رشد، ساختن توافقی است که هم استقلال و هم پاسخ دیگری را جا بدهد" },
  8: { thesis: "حرکت از امنیت شخصی به اعتماد، صمیمیت و سهم مشترک", bridge: "تمرین رشد، بیان سهم و نگرانی در فضایی است که کنترل کامل ممکن نیست" },
  9: { thesis: "حرکت از اطلاعات نزدیک به معنا، افق و موضع شخصی", bridge: "تمرین رشد، انتخاب یک جهت و اجازه دادن به تجربه برای تغییر باور است" },
  10: { thesis: "حرکت از امنیت خصوصی به مسئولیت و اثر بیرونی", bridge: "تمرین رشد، پذیرفتن نقشی است که نتیجه‌اش برای دیگران قابل مشاهده باشد" },
  11: { thesis: "حرکت از بیان فردی به دوستی، شبکه و آینده مشترک", bridge: "تمرین رشد، وصل کردن استعداد شخصی به همکاری بدون محو شدن در جمع است" },
  12: { thesis: "حرکت از وظیفه و کنترل روزانه به خلوت، استراحت و دریافت", bridge: "تمرین رشد، تحمل زمانی است که لازم نیست فوراً مفید یا حل‌کننده باشی" },
};
export function getCanonicalPlacementMatrixCounts() { return { planetSign: PLANET_SIGN_INTERACTIONS.length, planetHouse: PLANET_HOUSE_INTERACTIONS.length, signHouse: SIGN_HOUSE_INTERACTIONS.length, ascendantSigns: Object.keys(ASCENDANT_SIGN_SEMANTICS).length, nodeSignAxes: Object.keys(NODE_SIGN_AXIS_SEMANTICS).length, nodeHouseAxes: Object.keys(NODE_HOUSE_AXIS_SEMANTICS).length }; }